export const people = [
  {
    id: "cGVvcGxlOjE=",
    name: "Luke Skywalker",
    birthYear: "19BBY",
    gender: "male",
    species: null,
    homeworld: {
      name: "Tatooine",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjI=",
    name: "C-3PO",
    birthYear: "112BBY",
    gender: "n/a",
    species: {
      name: "Droid",
      __typename: "Species",
    },
    homeworld: {
      name: "Tatooine",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjM=",
    name: "R2-D2",
    birthYear: "33BBY",
    gender: "n/a",
    species: {
      name: "Droid",
      __typename: "Species",
    },
    homeworld: {
      name: "Naboo",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjQ=",
    name: "Darth Vader",
    birthYear: "41.9BBY",
    gender: "male",
    species: null,
    homeworld: {
      name: "Tatooine",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjU=",
    name: "Leia Organa",
    birthYear: "19BBY",
    gender: "female",
    species: null,
    homeworld: {
      name: "Alderaan",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjY=",
    name: "Owen Lars",
    birthYear: "52BBY",
    gender: "male",
    species: null,
    homeworld: {
      name: "Tatooine",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjc=",
    name: "Beru Whitesun lars",
    birthYear: "47BBY",
    gender: "female",
    species: null,
    homeworld: {
      name: "Tatooine",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjg=",
    name: "R5-D4",
    birthYear: "unknown",
    gender: "n/a",
    species: {
      name: "Droid",
      __typename: "Species",
    },
    homeworld: {
      name: "Tatooine",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjk=",
    name: "Biggs Darklighter",
    birthYear: "24BBY",
    gender: "male",
    species: null,
    homeworld: {
      name: "Tatooine",
      __typename: "Planet",
    },
    __typename: "Person",
  },
  {
    id: "cGVvcGxlOjEw",
    name: "Obi-Wan Kenobi",
    birthYear: "57BBY",
    gender: "male",
    species: null,
    homeworld: {
      name: "Stewjon",
      __typename: "Planet",
    },
    __typename: "Person",
  },
];
